pipeline {
    agent { 
        docker { 
            image 'python:3.8'
            args '-u root:root'
        }
    }
    stages {
        stage('install requirements') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }
        stage('run pytest') {
            steps {
                sh 'pytest -vv .'
            }   
        }
        stage('deploy') {
            when {
                branch "master"
            }
            steps {
                echo "This is master branch"
            }
        }
    }
}